name: Call Reusable Workflow
 
on:
  push:
    branches:
      - main
 
jobs:
  invoke-reusable-workflow:
    uses: ./.github/workflows/ReusableBuild.yml  # Call the reusable workflow
    with:
      var1: '16'     
      var2: true
