name: variable_condition_check
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  if-Windows-else:
    runs-on: macos-latest
    steps:
      - name: condition 1
        if: runner.os == 'Windows'
        run: echo "${{  github.actor }} triggered job on ${{ github.repository }} repo on $env:RUNNER_OS at $(date)."
      - name: condition 2
        if: runner.os != 'Windows'
        run: echo "${{  github.actor }} triggered job on ${{ github.repository }} repo on non windows OS ie ${{github.RUNNER_OS}} at $(date)."
      - name: print OS name 
        run: echo ${{github.RUNNER_OS}}
     
